import 'core-js/stable'
import 'core-js/proposals/promise-with-resolvers'
import Head from 'next/head'
import Header from './view/header'
import dynamic from 'next/dynamic'
// import Content from './view/content'
import Tail from './view/tail'

const Content = dynamic(() => import('./view/content'), {
  ssr: false,
})
export default function Home() {
  return (
    <div>
      <Head>
        <title>PDF.ai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content />
      <Tail />
    </div>
  )
}
